spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ecommerce
    password: Ecommerce@123

  jpa:
    hibernate:
      ddl-auto: update

  main:
    banner-mode: off

logging:
  level:
    root: warn

